<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AboutCardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutCardsRepository extends EntityRepository
{
    public function getCards()
    {
        $qb = $this->createQueryBuilder('ac')
            ->select('ac')
            ->addOrderBy('ac.id', 'ASC')
        ;

        return $qb->getQuery()
            ->getResult();
    }
}
