<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutRepository extends EntityRepository
{
    public function getAbout()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.status = true')
            ->addOrderBy('a.id', 'ASC')
        ;

        return $qb->getQuery()
            ->getResult();
    }
}
