<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DestinationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationsRepository extends EntityRepository
{
    public function getDestinations()
    {
        $qb = $this->createQueryBuilder('d')
            ->select('d')
            ->addOrderBy('d.id', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }
}
