<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomeSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeSliderRepository extends EntityRepository
{
    public function getSlider()
    {
        $qb = $this->createQueryBuilder('hs')
            ->select('hs')
            ->addOrderBy('hs.id', 'ASC')
        ;

        return $qb->getQuery()
            ->getResult();
    }
}
