<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamSocialMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamSocialMediaRepository extends EntityRepository
{
    public function getSM($team_id)
    {
        $qb = $this->createQueryBuilder('tsm')
            ->select('tsm')
            ->where('tsm.team_id = :team_id')
            ->addOrderBy('tsm.id', 'ASC')
            ->setParameter('team_id', $team_id)
        ;

        return $qb->getQuery()
            ->getResult()
            ;
    }
}
