<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function getTeam()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->addOrderBy('t.id', 'ASC')
        ;

        return $qb->getQuery()
            ->getResult();
    }
}
