<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use FOS\MessageBundle\Model\ParticipantInterface;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser implements ParticipantInterface
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $whatsapp
     */
    private $whatsapp;

    /**
     * @var string $viber
     */
    private $viber;

    /**
     * @var string $photo
     */
    protected $photo;


    public function __toString()
    {
       if(strlen($this->firstname) > 0 || strlen($this->lastname) > 0){
           return $this->firstname.' '.$this->lastname;
       }
       else return $this->username;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getWhatsapp()
    {
        return $this->whatsapp;
    }

    /**
     * @param string $whatsapp
     */
    public function setWhatsapp($whatsapp)
    {
        $this->whatsapp = $whatsapp;
    }

    /**
     * @return string
     */
    public function getViber()
    {
        return $this->viber;
    }

    /**
     * @param string $viber
     */
    public function setViber($viber)
    {
        $this->viber = $viber;
    }

    /**
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param string $photo
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

}